// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIBHtHxsDPw-MYwwHkx3oCfWnT--5loGc',
    appId: '1:577733338609:web:2b074e102ea75b74709050',
    messagingSenderId: '577733338609',
    projectId: 'estinol2',
    authDomain: 'estinol2.firebaseapp.com',
    storageBucket: 'estinol2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr1xv8f3rGIEzA-jaLbuCK9coXGdnmAJM',
    appId: '1:577733338609:android:0ffd494abd0c99de709050',
    messagingSenderId: '577733338609',
    projectId: 'estinol2',
    storageBucket: 'estinol2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcny65A2cLJE1CdX7qnlNG2Qc-EB4lqLM',
    appId: '1:577733338609:ios:d3855350ea0d02fb709050',
    messagingSenderId: '577733338609',
    projectId: 'estinol2',
    storageBucket: 'estinol2.firebasestorage.app',
    iosBundleId: 'com.example.estinol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcny65A2cLJE1CdX7qnlNG2Qc-EB4lqLM',
    appId: '1:577733338609:ios:d3855350ea0d02fb709050',
    messagingSenderId: '577733338609',
    projectId: 'estinol2',
    storageBucket: 'estinol2.firebasestorage.app',
    iosBundleId: 'com.example.estinol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIBHtHxsDPw-MYwwHkx3oCfWnT--5loGc',
    appId: '1:577733338609:web:64951914dca3dcf4709050',
    messagingSenderId: '577733338609',
    projectId: 'estinol2',
    authDomain: 'estinol2.firebaseapp.com',
    storageBucket: 'estinol2.firebasestorage.app',
  );
}
